#!/bin/bash
set -e

# Enable and start the service
if [ "$1" = "configure" ]; then
    systemctl daemon-reload
    systemctl enable quantix-kvm-agent.service
    systemctl start quantix-kvm-agent.service || true
fi

#DEBHELPER#

exit 0
