#!/bin/bash
set -e

# Stop the service before removal
if [ "$1" = "remove" ] || [ "$1" = "upgrade" ]; then
    systemctl stop limiquantix-agent.service || true
    systemctl disable limiquantix-agent.service || true
fi

#DEBHELPER#

exit 0
