// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file Quantixkvm/network/v1/network_service.proto (package Quantixkvm.network.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddConnectionRequest, AddListenerRequest, AddPoolMemberRequest, AddRuleRequest, AllocateFloatingIpRequest, AssociateFloatingIpRequest, BindPortRequest, CreateLoadBalancerRequest, CreateNetworkRequest, CreatePortRequest, CreateSecurityGroupRequest, CreateVpnRequest, DeleteLoadBalancerRequest, DeleteNetworkRequest, DeletePortRequest, DeleteSecurityGroupRequest, DeleteVpnRequest, DisassociateFloatingIpRequest, GetFloatingIpRequest, GetLoadBalancerRequest, GetLoadBalancerStatsRequest, GetNetworkRequest, GetNetworkTopologyRequest, GetPortRequest, GetSecurityGroupRequest, GetVpnRequest, GetVpnStatusRequest, ListFloatingIpsRequest, ListFloatingIpsResponse, ListLoadBalancersRequest, ListLoadBalancersResponse, ListNetworksRequest, ListNetworksResponse, ListPortsRequest, ListPortsResponse, ListSecurityGroupsRequest, ListSecurityGroupsResponse, ListVpnsRequest, ListVpnsResponse, LoadBalancerStats, NetworkTopology, ReleaseFloatingIpRequest, RemoveConnectionRequest, RemoveListenerRequest, RemovePoolMemberRequest, RemoveRuleRequest, UnbindPortRequest, UpdateLoadBalancerRequest, UpdateNetworkRequest, UpdatePortRequest, UpdateSecurityGroupRequest, VpnTunnelStatus } from "./network_service_pb";
import { FloatingIp, LoadBalancer, Port, SecurityGroup, VirtualNetwork, VpnService } from "./network_pb";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * VirtualNetworkService manages software-defined networks.
 *
 * @generated from service Quantixkvm.network.v1.VirtualNetworkService
 */
export const VirtualNetworkService = {
  typeName: "Quantixkvm.network.v1.VirtualNetworkService",
  methods: {
    /**
     * CreateNetwork creates a new virtual network.
     *
     * @generated from rpc Quantixkvm.network.v1.VirtualNetworkService.CreateNetwork
     */
    createNetwork: {
      name: "CreateNetwork",
      I: CreateNetworkRequest,
      O: VirtualNetwork,
      kind: MethodKind.Unary,
    },
    /**
     * GetNetwork retrieves a network by ID.
     *
     * @generated from rpc Quantixkvm.network.v1.VirtualNetworkService.GetNetwork
     */
    getNetwork: {
      name: "GetNetwork",
      I: GetNetworkRequest,
      O: VirtualNetwork,
      kind: MethodKind.Unary,
    },
    /**
     * ListNetworks returns all networks.
     *
     * @generated from rpc Quantixkvm.network.v1.VirtualNetworkService.ListNetworks
     */
    listNetworks: {
      name: "ListNetworks",
      I: ListNetworksRequest,
      O: ListNetworksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateNetwork updates network configuration.
     *
     * @generated from rpc Quantixkvm.network.v1.VirtualNetworkService.UpdateNetwork
     */
    updateNetwork: {
      name: "UpdateNetwork",
      I: UpdateNetworkRequest,
      O: VirtualNetwork,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteNetwork removes a network.
     * Network must have no ports unless force=true.
     *
     * @generated from rpc Quantixkvm.network.v1.VirtualNetworkService.DeleteNetwork
     */
    deleteNetwork: {
      name: "DeleteNetwork",
      I: DeleteNetworkRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * GetNetworkTopology returns network connectivity graph.
     *
     * @generated from rpc Quantixkvm.network.v1.VirtualNetworkService.GetNetworkTopology
     */
    getNetworkTopology: {
      name: "GetNetworkTopology",
      I: GetNetworkTopologyRequest,
      O: NetworkTopology,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * PortService manages network port connections.
 *
 * @generated from service Quantixkvm.network.v1.PortService
 */
export const PortService = {
  typeName: "Quantixkvm.network.v1.PortService",
  methods: {
    /**
     * CreatePort creates a new network port.
     *
     * @generated from rpc Quantixkvm.network.v1.PortService.CreatePort
     */
    createPort: {
      name: "CreatePort",
      I: CreatePortRequest,
      O: Port,
      kind: MethodKind.Unary,
    },
    /**
     * GetPort retrieves a port by ID.
     *
     * @generated from rpc Quantixkvm.network.v1.PortService.GetPort
     */
    getPort: {
      name: "GetPort",
      I: GetPortRequest,
      O: Port,
      kind: MethodKind.Unary,
    },
    /**
     * ListPorts returns ports with filtering.
     *
     * @generated from rpc Quantixkvm.network.v1.PortService.ListPorts
     */
    listPorts: {
      name: "ListPorts",
      I: ListPortsRequest,
      O: ListPortsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdatePort updates port configuration.
     *
     * @generated from rpc Quantixkvm.network.v1.PortService.UpdatePort
     */
    updatePort: {
      name: "UpdatePort",
      I: UpdatePortRequest,
      O: Port,
      kind: MethodKind.Unary,
    },
    /**
     * DeletePort removes a port.
     *
     * @generated from rpc Quantixkvm.network.v1.PortService.DeletePort
     */
    deletePort: {
      name: "DeletePort",
      I: DeletePortRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * BindPort assigns a port to a VM.
     *
     * @generated from rpc Quantixkvm.network.v1.PortService.BindPort
     */
    bindPort: {
      name: "BindPort",
      I: BindPortRequest,
      O: Port,
      kind: MethodKind.Unary,
    },
    /**
     * UnbindPort removes port assignment.
     *
     * @generated from rpc Quantixkvm.network.v1.PortService.UnbindPort
     */
    unbindPort: {
      name: "UnbindPort",
      I: UnbindPortRequest,
      O: Port,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * SecurityGroupService manages firewall rules.
 *
 * @generated from service Quantixkvm.network.v1.SecurityGroupService
 */
export const SecurityGroupService = {
  typeName: "Quantixkvm.network.v1.SecurityGroupService",
  methods: {
    /**
     * CreateSecurityGroup creates a new security group.
     *
     * @generated from rpc Quantixkvm.network.v1.SecurityGroupService.CreateSecurityGroup
     */
    createSecurityGroup: {
      name: "CreateSecurityGroup",
      I: CreateSecurityGroupRequest,
      O: SecurityGroup,
      kind: MethodKind.Unary,
    },
    /**
     * GetSecurityGroup retrieves a security group by ID.
     *
     * @generated from rpc Quantixkvm.network.v1.SecurityGroupService.GetSecurityGroup
     */
    getSecurityGroup: {
      name: "GetSecurityGroup",
      I: GetSecurityGroupRequest,
      O: SecurityGroup,
      kind: MethodKind.Unary,
    },
    /**
     * ListSecurityGroups returns all security groups.
     *
     * @generated from rpc Quantixkvm.network.v1.SecurityGroupService.ListSecurityGroups
     */
    listSecurityGroups: {
      name: "ListSecurityGroups",
      I: ListSecurityGroupsRequest,
      O: ListSecurityGroupsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateSecurityGroup updates rules.
     *
     * @generated from rpc Quantixkvm.network.v1.SecurityGroupService.UpdateSecurityGroup
     */
    updateSecurityGroup: {
      name: "UpdateSecurityGroup",
      I: UpdateSecurityGroupRequest,
      O: SecurityGroup,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteSecurityGroup removes a security group.
     * Group must not be in use unless force=true.
     *
     * @generated from rpc Quantixkvm.network.v1.SecurityGroupService.DeleteSecurityGroup
     */
    deleteSecurityGroup: {
      name: "DeleteSecurityGroup",
      I: DeleteSecurityGroupRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * AddRule adds a firewall rule.
     *
     * @generated from rpc Quantixkvm.network.v1.SecurityGroupService.AddRule
     */
    addRule: {
      name: "AddRule",
      I: AddRuleRequest,
      O: SecurityGroup,
      kind: MethodKind.Unary,
    },
    /**
     * RemoveRule removes a firewall rule.
     *
     * @generated from rpc Quantixkvm.network.v1.SecurityGroupService.RemoveRule
     */
    removeRule: {
      name: "RemoveRule",
      I: RemoveRuleRequest,
      O: SecurityGroup,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * FloatingIpService manages public IP assignments.
 *
 * @generated from service Quantixkvm.network.v1.FloatingIpService
 */
export const FloatingIpService = {
  typeName: "Quantixkvm.network.v1.FloatingIpService",
  methods: {
    /**
     * AllocateFloatingIp reserves a public IP.
     *
     * @generated from rpc Quantixkvm.network.v1.FloatingIpService.AllocateFloatingIp
     */
    allocateFloatingIp: {
      name: "AllocateFloatingIp",
      I: AllocateFloatingIpRequest,
      O: FloatingIp,
      kind: MethodKind.Unary,
    },
    /**
     * GetFloatingIp retrieves a floating IP by ID.
     *
     * @generated from rpc Quantixkvm.network.v1.FloatingIpService.GetFloatingIp
     */
    getFloatingIp: {
      name: "GetFloatingIp",
      I: GetFloatingIpRequest,
      O: FloatingIp,
      kind: MethodKind.Unary,
    },
    /**
     * ListFloatingIps returns all floating IPs.
     *
     * @generated from rpc Quantixkvm.network.v1.FloatingIpService.ListFloatingIps
     */
    listFloatingIps: {
      name: "ListFloatingIps",
      I: ListFloatingIpsRequest,
      O: ListFloatingIpsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ReleaseFloatingIp releases a public IP.
     *
     * @generated from rpc Quantixkvm.network.v1.FloatingIpService.ReleaseFloatingIp
     */
    releaseFloatingIp: {
      name: "ReleaseFloatingIp",
      I: ReleaseFloatingIpRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * AssociateFloatingIp assigns a floating IP to a port.
     *
     * @generated from rpc Quantixkvm.network.v1.FloatingIpService.AssociateFloatingIp
     */
    associateFloatingIp: {
      name: "AssociateFloatingIp",
      I: AssociateFloatingIpRequest,
      O: FloatingIp,
      kind: MethodKind.Unary,
    },
    /**
     * DisassociateFloatingIp removes a floating IP assignment.
     *
     * @generated from rpc Quantixkvm.network.v1.FloatingIpService.DisassociateFloatingIp
     */
    disassociateFloatingIp: {
      name: "DisassociateFloatingIp",
      I: DisassociateFloatingIpRequest,
      O: FloatingIp,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * LoadBalancerService manages load balancers.
 *
 * @generated from service Quantixkvm.network.v1.LoadBalancerService
 */
export const LoadBalancerService = {
  typeName: "Quantixkvm.network.v1.LoadBalancerService",
  methods: {
    /**
     * CreateLoadBalancer creates a new load balancer.
     *
     * @generated from rpc Quantixkvm.network.v1.LoadBalancerService.CreateLoadBalancer
     */
    createLoadBalancer: {
      name: "CreateLoadBalancer",
      I: CreateLoadBalancerRequest,
      O: LoadBalancer,
      kind: MethodKind.Unary,
    },
    /**
     * GetLoadBalancer retrieves a load balancer by ID.
     *
     * @generated from rpc Quantixkvm.network.v1.LoadBalancerService.GetLoadBalancer
     */
    getLoadBalancer: {
      name: "GetLoadBalancer",
      I: GetLoadBalancerRequest,
      O: LoadBalancer,
      kind: MethodKind.Unary,
    },
    /**
     * ListLoadBalancers returns all load balancers.
     *
     * @generated from rpc Quantixkvm.network.v1.LoadBalancerService.ListLoadBalancers
     */
    listLoadBalancers: {
      name: "ListLoadBalancers",
      I: ListLoadBalancersRequest,
      O: ListLoadBalancersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateLoadBalancer updates configuration.
     *
     * @generated from rpc Quantixkvm.network.v1.LoadBalancerService.UpdateLoadBalancer
     */
    updateLoadBalancer: {
      name: "UpdateLoadBalancer",
      I: UpdateLoadBalancerRequest,
      O: LoadBalancer,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteLoadBalancer removes a load balancer.
     *
     * @generated from rpc Quantixkvm.network.v1.LoadBalancerService.DeleteLoadBalancer
     */
    deleteLoadBalancer: {
      name: "DeleteLoadBalancer",
      I: DeleteLoadBalancerRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * AddListener adds a frontend listener.
     *
     * @generated from rpc Quantixkvm.network.v1.LoadBalancerService.AddListener
     */
    addListener: {
      name: "AddListener",
      I: AddListenerRequest,
      O: LoadBalancer,
      kind: MethodKind.Unary,
    },
    /**
     * RemoveListener removes a listener.
     *
     * @generated from rpc Quantixkvm.network.v1.LoadBalancerService.RemoveListener
     */
    removeListener: {
      name: "RemoveListener",
      I: RemoveListenerRequest,
      O: LoadBalancer,
      kind: MethodKind.Unary,
    },
    /**
     * AddPoolMember adds a backend member.
     *
     * @generated from rpc Quantixkvm.network.v1.LoadBalancerService.AddPoolMember
     */
    addPoolMember: {
      name: "AddPoolMember",
      I: AddPoolMemberRequest,
      O: LoadBalancer,
      kind: MethodKind.Unary,
    },
    /**
     * RemovePoolMember removes a backend member.
     *
     * @generated from rpc Quantixkvm.network.v1.LoadBalancerService.RemovePoolMember
     */
    removePoolMember: {
      name: "RemovePoolMember",
      I: RemovePoolMemberRequest,
      O: LoadBalancer,
      kind: MethodKind.Unary,
    },
    /**
     * GetLoadBalancerStats returns traffic statistics.
     *
     * @generated from rpc Quantixkvm.network.v1.LoadBalancerService.GetLoadBalancerStats
     */
    getLoadBalancerStats: {
      name: "GetLoadBalancerStats",
      I: GetLoadBalancerStatsRequest,
      O: LoadBalancerStats,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * VpnServiceManager manages site-to-site VPNs.
 *
 * @generated from service Quantixkvm.network.v1.VpnServiceManager
 */
export const VpnServiceManager = {
  typeName: "Quantixkvm.network.v1.VpnServiceManager",
  methods: {
    /**
     * CreateVpn creates a new VPN service.
     *
     * @generated from rpc Quantixkvm.network.v1.VpnServiceManager.CreateVpn
     */
    createVpn: {
      name: "CreateVpn",
      I: CreateVpnRequest,
      O: VpnService,
      kind: MethodKind.Unary,
    },
    /**
     * GetVpn retrieves a VPN service by ID.
     *
     * @generated from rpc Quantixkvm.network.v1.VpnServiceManager.GetVpn
     */
    getVpn: {
      name: "GetVpn",
      I: GetVpnRequest,
      O: VpnService,
      kind: MethodKind.Unary,
    },
    /**
     * ListVpns returns all VPN services.
     *
     * @generated from rpc Quantixkvm.network.v1.VpnServiceManager.ListVpns
     */
    listVpns: {
      name: "ListVpns",
      I: ListVpnsRequest,
      O: ListVpnsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteVpn removes a VPN service.
     *
     * @generated from rpc Quantixkvm.network.v1.VpnServiceManager.DeleteVpn
     */
    deleteVpn: {
      name: "DeleteVpn",
      I: DeleteVpnRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * AddConnection adds a VPN connection.
     *
     * @generated from rpc Quantixkvm.network.v1.VpnServiceManager.AddConnection
     */
    addConnection: {
      name: "AddConnection",
      I: AddConnectionRequest,
      O: VpnService,
      kind: MethodKind.Unary,
    },
    /**
     * RemoveConnection removes a VPN connection.
     *
     * @generated from rpc Quantixkvm.network.v1.VpnServiceManager.RemoveConnection
     */
    removeConnection: {
      name: "RemoveConnection",
      I: RemoveConnectionRequest,
      O: VpnService,
      kind: MethodKind.Unary,
    },
    /**
     * GetVpnStatus returns VPN tunnel status.
     *
     * @generated from rpc Quantixkvm.network.v1.VpnServiceManager.GetVpnStatus
     */
    getVpnStatus: {
      name: "GetVpnStatus",
      I: GetVpnStatusRequest,
      O: VpnTunnelStatus,
      kind: MethodKind.Unary,
    },
  }
} as const;

